require("dahng.plugins-setup")

require("dahng.core.options")
require("dahng.core.keymaps")
require("dahng.core.colorscheme")

require("dahng.plugins.comment")
require("dahng.plugins.nvim-tree")
require("dahng.plugins.lualine")
require("dahng.plugins.telescope")
require("dahng.plugins.nvim-cmp")
require("dahng.plugins.autopairs")
require("dahng.plugins.treesitter")
require("dahng.plugins.gitsigns")
require("dahng.plugins.coc")

require("dahng.plugins.lsp.mason")
require("dahng.plugins.lsp.lspsaga")
require("dahng.plugins.lsp.lspconfig")
require("dahng.plugins.lsp.null-ls")
